name: iom_campus_app
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.2
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  file_picker: ^10.3.2
  path_provider: ^2.1.1
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true